In [6]:
import kagglehub

path = kagglehub.dataset_download("annavictoria/speed-dating-experiment")

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.13), please consider upgrading to the latest version (1.0.0).

In [7]:
import pandas as pd
file_path = path + "/Speed Dating Data.csv"
print(file_path)
df = pd.read_csv(file_path, encoding='latin-1')
df.head()

C:\Users\krhij\.cache\kagglehub\datasets\annavictoria\speed-dating-experiment\versions\1/Speed Dating Data.csv

,iid,id,gender,idg,condtn,wave,round,position,positin1,order,...,attr3_3,sinc3_3,intel3_3,fun3_3,amb3_3,attr5_3,sinc5_3,intel5_3,fun5_3,amb5_3
0,1,1.0,0,1,1,1,10,7,NaN,4,...,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
1,1,1.0,0,1,1,1,10,7,NaN,3,...,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
2,1,1.0,0,1,1,1,10,7,NaN,10,...,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
3,1,1.0,0,1,1,1,10,7,NaN,5,...,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
4,1,1.0,0,1,1,1,10,7,NaN,7,...,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN

In [15]:
#Time1
columns_Time1 = ['iid', 'pid']
for col in df.columns:
    if col.endswith('1_1'):
        columns_Time1.append(col)
df_pre_event = df[columns_Time1]

#Scorecard
columns_scorecard = ['iid', 'pid', 'attr', 'sinc', 'intel', 'fun', 'amb', 'shar', 'dec', 'match']
df_scorecard = df[columns_scorecard]

#Half-way
columns_Halfway = ['iid', 'pid']
for col in df.columns:
    if col.endswith('1_s'):
        columns_Halfway.append(col)
df_halfway = df[columns_Halfway]

#Time2
columns_Time2 = ['iid', 'pid']
for col in df.columns:
    if col.endswith('1_2'):
        columns_Time2.append(col)
df_day_after = df[columns_Time2]

#Time3
columns_Time3 = ['iid', 'pid']
for col in df.columns:
    if col.endswith('1_3'):
        columns_Time3.append(col)
df_weeks_later = df[columns_Time3]


print("Pre-Event Survey Data ---")
display(df_pre_event.head(3))

print("\nIn-Event Scorecard (The Date) ---")
display(df_scorecard.head(3))

print("\nHalfway Survey Data ---")
display(df_halfway.head(3))

print("\nDay-After Survey Data ---")
display(df_day_after.head(3))

print("\n3-4 Weeks Later Survey Data ---")
display(df_weeks_later.head(3))

Pre-Event Survey Data ---

   iid   pid  attr1_1  sinc1_1  intel1_1  fun1_1  amb1_1  shar1_1
0    1  11.0     15.0     20.0      20.0    15.0    15.0     15.0
1    1  12.0     15.0     20.0      20.0    15.0    15.0     15.0
2    1  13.0     15.0     20.0      20.0    15.0    15.0     15.0

In-Event Scorecard (The Date) ---

   iid   pid  attr  sinc  intel  fun  amb  shar  dec  match
0    1  11.0   6.0   9.0    7.0  7.0  6.0   5.0    1      0
1    1  12.0   7.0   8.0    7.0  8.0  5.0   6.0    1      0
2    1  13.0   5.0   8.0    9.0  8.0  5.0   7.0    1      1

Halfway Survey Data ---

   iid   pid  attr1_s  sinc1_s  intel1_s  fun1_s  amb1_s  shar1_s
0    1  11.0      NaN      NaN       NaN     NaN     NaN      NaN
1    1  12.0      NaN      NaN       NaN     NaN     NaN      NaN
2    1  13.0      NaN      NaN       NaN     NaN     NaN      NaN

Day-After Survey Data ---

   iid   pid  attr1_2  sinc1_2  intel1_2  fun1_2  amb1_2  shar1_2
0    1  11.0    19.44    16.67     13.89   22.22   11.11    16.67
1    1  12.0    19.44    16.67     13.89   22.22   11.11    16.67
2    1  13.0    19.44    16.67     13.89   22.22   11.11    16.67

3-4 Weeks Later Survey Data ---

   iid   pid  attr1_3  sinc1_3  intel1_3  fun1_3  amb1_3  shar1_3
0    1  11.0     15.0     20.0      20.0    15.0    15.0     15.0
1    1  12.0     15.0     20.0      20.0    15.0    15.0     15.0
2    1  13.0     15.0     20.0      20.0    15.0    15.0     15.0

In [8]:
print("Dataset Shape:", df.shape)

df.info(verbose=True, show_counts=True)

Dataset Shape: (8378, 195)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8378 entries, 0 to 8377
Data columns (total 195 columns):
 #    Column    Non-Null Count  Dtype
---   ------    --------------  -----
 0    iid       8378 non-null   int64
 1    id        8377 non-null   float64
 2    gender    8378 non-null   int64
 3    idg       8378 non-null   int64
 4    condtn    8378 non-null   int64
 5    wave      8378 non-null   int64
 6    round     8378 non-null   int64
 7    position  8378 non-null   int64
 8    positin1  6532 non-null   float64
 9    order     8378 non-null   int64
 10   partner   8378 non-null   int64
 11   pid       8368 non-null   float64
 12   match     8378 non-null   int64
 13   int_corr  8220 non-null   float64
 14   samerace  8378 non-null   int64
 15   age_o     8274 non-null   float64
 16   race_o    8305 non-null   float64
 17   pf_o_att  8289 non-null   float64
 18   pf_o_sin  8289 non-null   float64
 19   pf_o_int  8289 non-null   float64
 20   pf_o_fun  8280 non-null   float64
 21   pf_o_amb  8271 non-null   float64
 22   pf_o_sha  8249 non-null   float64
 23   dec_o     8378 non-null   int64
 24   attr_o    8166 non-null   float64
 25   sinc_o    8091 non-null   float64
 26   intel_o   8072 non-null   float64
 27   fun_o     8018 non-null   float64
 28   amb_o     7656 non-null   float64
 29   shar_o    7302 non-null   float64
 30   like_o    8128 non-null   float64
 31   prob_o    8060 non-null   float64
 32   met_o     7993 non-null   float64
 33   age       8283 non-null   float64
 34   field     8315 non-null   object
 35   field_cd  8296 non-null   float64
 36   undergra  4914 non-null   object
 37   mn_sat    3133 non-null   object
 38   tuition   3583 non-null   object
 39   race      8315 non-null   float64
 40   imprace   8299 non-null   float64
 41   imprelig  8299 non-null   float64
 42   from      8299 non-null   object
 43   zipcode   7314 non-null   object
 44   income    4279 non-null   object
 45   goal      8299 non-null   float64
 46   date      8281 non-null   float64
 47   go_out    8299 non-null   float64
 48   career    8289 non-null   object
 49   career_c  8240 non-null   float64
 50   sports    8299 non-null   float64
 51   tvsports  8299 non-null   float64
 52   exercise  8299 non-null   float64
 53   dining    8299 non-null   float64
 54   museums   8299 non-null   float64
 55   art       8299 non-null   float64
 56   hiking    8299 non-null   float64
 57   gaming    8299 non-null   float64
 58   clubbing  8299 non-null   float64
 59   reading   8299 non-null   float64
 60   tv        8299 non-null   float64
 61   theater   8299 non-null   float64
 62   movies    8299 non-null   float64
 63   concerts  8299 non-null   float64
 64   music     8299 non-null   float64
 65   shopping  8299 non-null   float64
 66   yoga      8299 non-null   float64
 67   exphappy  8277 non-null   float64
 68   expnum    1800 non-null   float64
 69   attr1_1   8299 non-null   float64
 70   sinc1_1   8299 non-null   float64
 71   intel1_1  8299 non-null   float64
 72   fun1_1    8289 non-null   float64
 73   amb1_1    8279 non-null   float64
 74   shar1_1   8257 non-null   float64
 75   attr4_1   6489 non-null   float64
 76   sinc4_1   6489 non-null   float64
 77   intel4_1  6489 non-null   float64
 78   fun4_1    6489 non-null   float64
 79   amb4_1    6489 non-null   float64
 80   shar4_1   6467 non-null   float64
 81   attr2_1   8299 non-null   float64
 82   sinc2_1   8299 non-null   float64
 83   intel2_1  8299 non-null   float64
 84   fun2_1    8299 non-null   float64
 85   amb2_1    8289 non-null   float64
 86   shar2_1   8289 non-null   float64
 87   attr3_1   8273 non-null   float64
 88   sinc3_1   8273 non-null   float64
 89   fun3_1    8273 non-null   float64
 90   intel3_1  8273 non-null   float64
 91   amb3_1    8273 non-null   float64
 92   attr5_1   4906 non-null   float64
 93   sinc5_1   4906 non-null   float64
 94   intel5_1  4906 non-null   float64
 95   fun5_1    4906 non-null   float64
 96   amb5_1    4906 non-null   float64
 97   dec       8378 non-null   int64
 98   attr      8176 non-null   float64
 99   sinc      8101 non-null   float64
 100  intel     8082 non-null   float64
 101  fun       8028 non-null   float64
 102  amb       7666 non-null   float64
 103  shar      7311 non-null   float64
 104  like      8138 non-null   float64
 105  prob      8069 non-null   float64
 106  met       8003 non-null   float64
 107  match_es  7205 non-null   float64
 108  attr1_s   4096 non-null   float64
 109  sinc1_s   4096 non-null   float64
 110  intel1_s  4096 non-null   float64
 111  fun1_s    4096 non-null   float64
 112  amb1_s    4096 non-null   float64
 113  shar1_s   4096 non-null   float64
 114  attr3_s   4000 non-null   float64
 115  sinc3_s   4000 non-null   float64
 116  intel3_s  4000 non-null   float64
 117  fun3_s    4000 non-null   float64
 118  amb3_s    4000 non-null   float64
 119  satis_2   7463 non-null   float64
 120  length    7463 non-null   float64
 121  numdat_2  7433 non-null   float64
 122  attr7_2   1984 non-null   float64
 123  sinc7_2   1955 non-null   float64
 124  intel7_2  1984 non-null   float64
 125  fun7_2    1984 non-null   float64
 126  amb7_2    1955 non-null   float64
 127  shar7_2   1974 non-null   float64
 128  attr1_2   7445 non-null   float64
 129  sinc1_2   7463 non-null   float64
 130  intel1_2  7463 non-null   float64
 131  fun1_2    7463 non-null   float64
 132  amb1_2    7463 non-null   float64
 133  shar1_2   7463 non-null   float64
 134  attr4_2   5775 non-null   float64
 135  sinc4_2   5775 non-null   float64
 136  intel4_2  5775 non-null   float64
 137  fun4_2    5775 non-null   float64
 138  amb4_2    5775 non-null   float64
 139  shar4_2   5775 non-null   float64
 140  attr2_2   5775 non-null   float64
 141  sinc2_2   5775 non-null   float64
 142  intel2_2  5775 non-null   float64
 143  fun2_2    5775 non-null   float64
 144  amb2_2    5775 non-null   float64
 145  shar2_2   5775 non-null   float64
 146  attr3_2   7463 non-null   float64
 147  sinc3_2   7463 non-null   float64
 148  intel3_2  7463 non-null   float64
 149  fun3_2    7463 non-null   float64
 150  amb3_2    7463 non-null   float64
 151  attr5_2   4377 non-null   float64
 152  sinc5_2   4377 non-null   float64
 153  intel5_2  4377 non-null   float64
 154  fun5_2    4377 non-null   float64
 155  amb5_2    4377 non-null   float64
 156  you_call  3974 non-null   float64
 157  them_cal  3974 non-null   float64
 158  date_3    3974 non-null   float64
 159  numdat_3  1496 non-null   float64
 160  num_in_3  668 non-null    float64
 161  attr1_3   3974 non-null   float64
 162  sinc1_3   3974 non-null   float64
 163  intel1_3  3974 non-null   float64
 164  fun1_3    3974 non-null   float64
 165  amb1_3    3974 non-null   float64
 166  shar1_3   3974 non-null   float64
 167  attr7_3   2016 non-null   float64
 168  sinc7_3   2016 non-null   float64
 169  intel7_3  2016 non-null   float64
 170  fun7_3    2016 non-null   float64
 171  amb7_3    2016 non-null   float64
 172  shar7_3   2016 non-null   float64
 173  attr4_3   2959 non-null   float64
 174  sinc4_3   2959 non-null   float64
 175  intel4_3  2959 non-null   float64
 176  fun4_3    2959 non-null   float64
 177  amb4_3    2959 non-null   float64
 178  shar4_3   2959 non-null   float64
 179  attr2_3   2959 non-null   float64
 180  sinc2_3   2959 non-null   float64
 181  intel2_3  2959 non-null   float64
 182  fun2_3    2959 non-null   float64
 183  amb2_3    2959 non-null   float64
 184  shar2_3   2016 non-null   float64
 185  attr3_3   3974 non-null   float64
 186  sinc3_3   3974 non-null   float64
 187  intel3_3  3974 non-null   float64
 188  fun3_3    3974 non-null   float64
 189  amb3_3    3974 non-null   float64
 190  attr5_3   2016 non-null   float64
 191  sinc5_3   2016 non-null   float64
 192  intel5_3  2016 non-null   float64
 193  fun5_3    2016 non-null   float64
 194  amb5_3    2016 non-null   float64
dtypes: float64(174), int64(13), object(8)
memory usage: 12.5+ MB

In [9]:
df.describe().T

           count        mean         std  min    25%    50%    75%    max
iid       8378.0  283.675937  158.583367  1.0  154.0  281.0  407.0  552.0
id        8377.0    8.960248    5.491329  1.0    4.0    8.0   13.0   22.0
gender    8378.0    0.500597    0.500029  0.0    0.0    1.0    1.0    1.0
idg       8378.0   17.327166   10.940735  1.0    8.0   16.0   26.0   44.0
condtn    8378.0    1.828837    0.376673  1.0    2.0    2.0    2.0    2.0
...          ...         ...         ...  ...    ...    ...    ...    ...
attr5_3   2016.0    6.810020    1.507341  2.0    6.0    7.0    8.0   10.0
sinc5_3   2016.0    7.615079    1.504551  2.0    7.0    8.0    9.0   10.0
intel5_3  2016.0    7.932540    1.340868  4.0    7.0    8.0    9.0   10.0
fun5_3    2016.0    7.155258    1.672787  1.0    6.0    7.0    8.0   10.0
amb5_3    2016.0    7.048611    1.717988  1.0    6.0    7.0    8.0   10.0

[187 rows x 8 columns]

In [10]:
missing_percentages = (df.isnull().sum() / len(df)) * 100
missing_data = missing_percentages[missing_percentages > 0].sort_values(ascending=False)

print("Columns with most missing data:")
print(missing_data.head(10))

Columns with most missing data:
num_in_3    92.026737
numdat_3    82.143710
expnum      78.515159
sinc7_2     76.665075
amb7_2      76.665075
shar7_2     76.438291
fun7_2      76.318931
attr7_2     76.318931
intel7_2    76.318931
amb7_3      75.936978
dtype: float64

In [11]:
print("Total Match Count:")
print(df['match'].value_counts())

print("\nMatch Percentage:")
print(df['match'].value_counts(normalize=True) * 100)

Total Match Count:
match
0    6998
1    1380
Name: count, dtype: int64

Match Percentage:
match
0    83.528288
1    16.471712
Name: proportion, dtype: float64